language: php
php:
  - "5.6"
# no dependency to install
#ZZgenda\pages\phpunit-5.6.1.phar ZZgenda\pages\TestCo.php

before_script:
  ##PHPUnit
  - mkdir -p build/logs
script:
  #PHPUnit
  - phpunit -c ./  --coverage-html ./pages #build/logs/clover.xml   --coverage-text

after_script:
  #Coveralls
  - php vendors/bin/coveralls -v


after_success:
# Submit coverage report to Coveralls servers, see .coveralls.yml
 - travis_retry php coveralls.phar -v
