<?php
$lang = array('identification' => array('login' => array('fr' => "Pseudo", 'en' => "Enter login"),
                                        'password' => array('fr' => "Mot de passe", 'en' => "Enter password"),
                                        'submit' => array('fr' => "Se connecter", 'en' => "Submit"),
                                        'authentification' => array('fr' => "Erreur d\'authentification", 'en' => "Authentification failure"),
                                        'database' => array('fr' => "Erreur dans l'ouverture du fichier 'database'", 'en' => "Failed to open 'database'"),
                                        'userAdd' => array('fr' => "Un nouvel utilisateur a été créé", "en" => "New user creation"),
                                        ),
              'calendrier' => array('available' => array('fr' => "Vérifier mon emploi du temps", 'en' => "Am I available ?"),
                                    'firstname' => array('fr' => "Prénom", 'en' => "Firstname"),
                                    'look' => array('fr' => "Jette un coup d'oeil", 'en' => "Let's have a look"),
                                    'School' => array('fr' => "Ecole", 'en' => "School"),
                                    'Disconnect' => array('fr' => "Deconnexion", 'en' => "Log out"),
                                    'lastname' => array('fr' => "Nom", 'en' => "Lastname")
                                  ),
              'ajout' => array('academic' => array('fr' => "Scolaire", 'en' => "Academic"),
                               'professionnal1' => array('fr' => "Professionnelle", 'en' => "Professionnal"),
                               'firstname' => array('fr' => "Prénom", 'en' => "Firstname"),
                               'lastname' => array('fr' => "Nom", 'en' => "Lastname"),
                               'conference' => array('fr' => "Titre de la conférence", 'en' => "Conference title"),
                               'youare' => array('fr' => "Vous êtes", 'en' => "You are"),
                               'professionnal2' => array('fr' => "Un professionnel", 'en' => "A professionnal"),
                               'external' => array('fr' => "Un particulier", 'en' => "An external"),
                               'institutional' => array('fr' => "Un institutionnel", 'en' => "An institution"),
                               'who' => array('fr' => "A qui s'adresse la conférence ?", 'en' => "Who is the conference for ?"),
                               'connoisseur' => array('fr' => "Connaisseurs", 'en' => "Connoisseurs"),
                               'anybody' => array('fr' => "Tout public", 'en' => "Anybody"),
                               'details' => array('fr' => "Détails :", 'en' => "Details:"),
                               'enterdetails' => array('fr' => "Saisissez les détails de la conférence", 'en' => "Type in the conference details"),
                               'date' => array('fr' => "Entrez la date et l'heure de la conférence", 'en' => "When is the conference ?"),
                               'day' => array('fr' => "JJ/MM/AAAA", 'en' => "DD/MM/YYYY"),
                               'hour' => array('fr' => "à", 'en' => "at"),
                               'jan' => array('fr' => "Jan", 'en' => "Jan"),
                               'feb' => array('fr' => "Fév", 'en' => "Feb"),
                               'mar' => array('fr' => "Mars", 'en' => "Mar"),
                               'apr' => array('fr' => "Avr", 'en' => "Apr"),
                               'may' => array('fr' => "Mai", 'en' => "May"),
                               'jun' => array('fr' => "Juin", 'en' => "Jun"),
                               'jul' => array('fr' => "Juil", 'en' => "Jul"),
                               'aug' => array('fr' => "Août", 'en' => "Aug"),
                               'sep' => array('fr' => "Sep", 'en' => "Sep"),
                               'oct' => array('fr' => "Oct", 'en' => "Oct"),
                               'nov' => array('fr' => "Nov", 'en' => "Nov"),
                               'dec' => array('fr' => "Déc", 'en' => "Dec"),
                               'submit' => array('fr' => "Valider", 'en' => "Submit"),
                               'Back' => array('fr' => "Retour page Admin", 'en' => "Back to Admin"),
                               'cancel' => array('fr' => "Annuler", 'en' => "Cancel")
                             ),
              'admin' => array('conference' => array('fr' => "Ajouter une conférence", 'en' => "Add a conference"),
                               'ConferenceAff' => array('fr' => "Conférence", 'en' => "Meeting"),
                               'Calendrier' => array('fr' => "Calendrier des conférences", 'en' => "Meeting planning"),
                               'hour' => array('fr' => "Heure", 'en' => "Hour"),
                               'date' => array('fr' => "Date", 'en' => "Date"),
                               'login' => array('fr' => "Identifiant", 'en' => "Login"),
                               'passw' => array('fr' => "Mot de passe", 'en' => "Passw"),
                               'level' => array('fr' => "Niveau", 'en' => "Level"),
                               'administrator' => array('fr' => "Administrateur", 'en' => "Administrator"),
                               'user' => array('fr' => "Utilisateur", 'en' => "User"),
                               'submit' => array('fr' => "Valider", 'en' => "Submit"),
                               'NewUser' => array('fr' => "Ajouter un utilisateur", 'en' => "Add user"),
                               'cancel' => array('fr' => "Annuler", 'en' => "Cancel")
                              )
             );
?>
